In [4]:
import numpy as np
a3 = np.random.rand(3,3) < 0.8


In [5]:
a3

array([[False, False,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [6]:
b3 =np.random.rand(3,3)

In [7]:
b3

array([[0.67386016, 0.06255053, 0.78116481],
       [0.63408737, 0.58535695, 0.52498228],
       [0.65003902, 0.68025674, 0.63350436]])

In [9]:
c3 = np.multiply(a3,b3)

In [10]:
c3

array([[0.        , 0.        , 0.78116481],
       [0.63408737, 0.58535695, 0.52498228],
       [0.65003902, 0.68025674, 0.63350436]])